apiVersion: v1
kind: Secret
metadata:
  name: truenas-nfs-driver-config
  namespace: storage
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:s9kxOGSb78tAj4bHTyQjx7B5eVeJnh0Jwhfr3teQ6RW72B66zCfHfaQBq73hj3d8vnimBxCt4Ho1OtTmlhL+i+R6cgMAUS83Q6tWICucpRooonCPnwcjkOY4AinkxrGBBxi2PzBtsv+oaiJ5OOA6c9t/VldBwkCnIKq+nn+fulfTweLiAwK7VT96jHQlmazlH3IoDTZupjErl+b8TZwOsz9HNBI7maKb5CF0ZamYSqdlr+2KLFNPv6Rz/z2TR0WqC4CX1r76XNEiECocUlQ/i6XRRmG77qjqH7UtkrMXEWBFvyNh04TCqXHF/gR8z0Mrk2r4HA0GrowySRqRcvvqtGlalImsmP+rLUF1+O5Y9NMLNnUsL6NBurXWBuwjwjg5zVnfm4utIR4RD33zDWMux6PNgDodOPDz75Vvr5ODa5OmGQViylKmm8RuX12nc04l0uJuXMQFC45IyWo4MvpWAukDVvFu3N+B2BnwDjK5JoMAC/8ES+YA/vgcHPUVRLrYYWdZiiC6r8z4H7mQ+0c9EnHtYSfQGiVLwlVRaMYEzvG2GDNXscwtYPy+UWIS10ceF9CFc9RX4+opD99fTvok00AfldlIqSMEaaREW1rg/DNMEk5y5CnCpa17vKm2YNJIv6zposKQL239UMmenMLYacXqk0LDPUhaua9kynJewRhtJMZbeFyYE1pUjam7aTm2/fGxNUakOiTQ/j82QyFfmwXkyAlaLAda/ZTITARXh0WMdkjhsaVMaQFgoadT7pYXLQDg+rkx0/7KhCX/DTid3kiFi/WcmTjK4dFIVha5c4I+pYXYkFLhxTHrOBp/6S43WMFCpNQt9KWrCet6Un8oifX3oKdznN+SqSZVezYcq5+QGpQBmOjgYLjrCF3LrkckCpYIRlqSsHHwYyg77fqNV++Vcq3JooTGUNMGoCo3blJTdHltjPpq1FHvfcqrrxK0HH1emwdjAOmSutDxOT0uUmLymCwxiChoIB2FOHTaqE6HelZqev9+ey4CKAXnFijRHkDN502mpBOX2hFkISI44HxsIrAMe02mVCHfFvHKI6/u+uirxXgOkvzzIumnb0aFA2bQbc1BEfngn1Wbbv9CegBic67Dhg1eh/CJibIkugrMmdB0wtsb/Nsjj0+UWvFyJFfVAYOqo8GmC6Mv58STcUc4n1cKLPcWI/lWoEN1HlpBccGert4/zBPDqHc=,iv:F/MoT5tTmGvGwnR3i5ETQdj5bcojNhjnR/q3hzZi0hk=,tag:OiBfR3HTf0qplRYhzB/QCQ==,type:str]
sops:
  age:
    - recipient: age1qlgzet5vmw8vfxa2456rx5t6uhhjcph7qwwtlsq7x7ry8ytgsv4s5rmw8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MWRqbmh4NkNoUWNoU2E0
        Ym9OUFBYbjg3d1p6S2hMQ2tZNjB5bjJBSmg0CmVoVDI2ZzJyQXpMeHVnbXNaV1JT
        TDFHOU9NMWVlRFNWbVFMb20yZnVnZDQKLS0tICs1RFVpUUdReitZRmJsSm1tZDVI
        Ny96WmdWNjFHUllnelVybFk4Um51UHcKLnSGb1zOjWzc8neYg3VCnYmv4bVgvmPf
        ZvT62lHJS7wDNJLvx/Lqai5/YJsyBdTF+nrIQjKFiGQkk8k6kqBgow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T10:55:33Z"
  mac: ENC[AES256_GCM,data:QvbqkqpZzIvbrjlmCBtWVNDUcu0kEUPwIPUZt6Ww8VUarSJYJZIZR4xGdW94uJO4OPmpVsxFq4PcEkBZMjXvBDjtICZywTLsC6iWnoZPUQszJrDO9a9ihsjuaeEqmIxeAyb5bigmkIciraG6UgPglG82OmTG3z2J9O+S2oTuK70=,iv:tpEz7NjP3b5OCE65v9p03RLaKgjPzXKtCIz6Nwr4Ekg=,tag:r1NUZBAjlBvOa/5QFuHQxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
