apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vevjCNFQu2KpAjjdWu1o/fHUOUkavnlyz65MxzSJ+KH7aBEcPXELYA==,iv:9TFaTvhUPA+bAisdH7MYbrTU2361qqVtoPnPGOMvvPQ=,tag:xST5wfqmWAH/4dJ1BsttGA==,type:str]
sops:
  age:
    - recipient: age1qlgzet5vmw8vfxa2456rx5t6uhhjcph7qwwtlsq7x7ry8ytgsv4s5rmw8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSG1yMEZmaE5pTXhydlVU
        MURLdlNEOG9VZFlyVFlrSlRaOG8ySitJamlJCmRObzNWTVcvTkU5MTAxQy9GUTFF
        OVVNL1A0QXRYdUwySStDZjNKVGc0WWsKLS0tIFNxU3o1dWlLNkVqWmI2TkZDSnVs
        ZmlHLzMxVHZPNXdSK1BiZ094bnBEY1UKmBrYw4F7KCTAXYlklcJCGA3vYr1p0nnU
        fU2ABAV1kkJiq9Ahy5FYsP8BGNttU8l0sbVQ4dk1Iy04roWlhayQeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T06:13:48Z"
  mac: ENC[AES256_GCM,data:rUgWI7SDe6BPpHCBf58Wpzj+yh10Amd7lNO32HoKMfTKbYEj0VegC37Wv8WgrrKs8ugCNmWUY/xwLIyYGpw/Z/XScrEIh5aYgaINRgZOTXJRhtyxuTYKXMVQsvJ0wFgF5jLbIkWrnyAh+WApyoBAAbNQ9PteJhY4TtOEUlhiC90=,iv:6V+UFY9PdpxA0nxp0kkTomNTlGeRrXqUtiY50f31lCo=,tag:J/m3534I+mF8vIPFrH4raQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
