apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:4K6AbC9P4I3HmHRbHw==,iv:dfeqq/FSfEaSkYmag4U0u58OtN/ATuDixsBR7mdw4n4=,tag:2UXue/rWrBYDUeyKn5yTgQ==,type:str]
sops:
  age:
    - recipient: age1qlgzet5vmw8vfxa2456rx5t6uhhjcph7qwwtlsq7x7ry8ytgsv4s5rmw8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSkNNazJmeVhNQWZuYXli
        aGgvYkREODlkNmRGWGlmN0FnN1pJZUJLQVhRCnd3TlFobi83UHA0K1B1YlVzaVFN
        RzZhZjJad0d2VUhoY2dlemppUUhDYWMKLS0tIGJaWVJ6SmVyNUU5bTR4cnM0S3F2
        U3YwZEdVYVBvYk4vK2xYMGdRWk9wU2MK2+Fi0ijz1mDA+c4qhG7Yiu6oDVv0iXxs
        Q7IwYyuEeXmem2SGPoo39YMdfyL/pQgUydXQQ0ON7qPy3+gGzVST/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T06:13:48Z"
  mac: ENC[AES256_GCM,data:aEkR3JcANz4D/FUkhRcQpE81Qcg5ocgm4h393XAPmxf0oeJHmoBNYSdL78fG+V4ImCDvfaq40WGsYnfQambviPkDBZ49rAAJurPq+CQ2frde9hZnE1m6/rOPzAPDVDVq26lMaXFBjShfQVsqlrxpN/3lLUo2APddVCp/CaOyPc0=,iv:J4qEqEK7IiMhs+J6a61/dHoJULQvdlxwO0MGEZychhU=,tag:1ItHQs5EkW3DU+TCPUlnzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
