apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:43e8P6x6Rj/FPK4Fi49KiqeDSx/f6EjxUkYuaU5yvE8=,iv:ENzt6qQrasKVcguM7MN1R1TOAvHnd9qzpm5JG3e3Wsg=,tag:CWWZ3LF5WG7sSKNGe0wYTw==,type:str]
sops:
  age:
    - recipient: age1qlgzet5vmw8vfxa2456rx5t6uhhjcph7qwwtlsq7x7ry8ytgsv4s5rmw8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S2g3UzJ4Q1dBdVgrUFZk
        alhKQTM0Uk5aaWNwQ1p6bk8xYWtmVjkra2dNCmhJWjJOaE9CY1NuaFJBSWc1Ukll
        c1Z2LzIrNlhpRVpCWmhGYWkvSlFGWnMKLS0tIG5IcmJNYUYyOWdFSm5BUjNnRTBm
        Z1dqMjJNZmk0UDIrbHV2UXFqcGJ6Mk0Ks6eXmSePH5RhzWlWZXENJy6U05oEMGR7
        PanjuBJ8PG/d/C2XPsa/5JEsZZk8xoZuVOmsXPKRkC7ci+jorRMczg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T06:13:48Z"
  mac: ENC[AES256_GCM,data:/iuTHBK8jtfKJI9DHXnNexDn752qsY/MJAnAgvmydVe6eK27kLdVRLHr9trr+DruWI9Zj0O+u9isoULPWx8xIHPiFEv30sWrFlN7j4gKDUUZSRhBiyDBPE13gPbMq/tr0ROp9bGX+jni7zI7mdg2OxTTTp7R40HSY5X9YSwku/Y=,iv:AUznldf1gAlm6rAyuD/MJ6k0tlx0aGRIIvAHTDrs3dE=,tag:VRE1XsgqIjwHHdG66WU8Ig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
