apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KrHcEkVXXsM6faWBOTJ2of0gDJ3d1vKHdHQi236BBCUu0PPrcpPaVHrs3hzBUgkm9Ernf7U4CM9yA/usjS0rvF9hJrl+Nb066ZOeGohxMTzQpbuTuogW+uGBpZ2emW1CcX48dUFBsy9bfqSVWAzS53uCXtW2G4/YFmTCLZsSmrpFlYvyxwals6jJGwRjZZ6dA+vbB0hhtZng5Z7H9iDnSTTSPY6rrWITvT8HVVgEsCVMDpf1,iv:Aq0wR6LH0lT5zBjW+dzm7vN0hYKSt0nSQvZ2g789/Cg=,tag:O/a7soncV97JJVioGkuWFg==,type:str]
sops:
  age:
    - recipient: age1qlgzet5vmw8vfxa2456rx5t6uhhjcph7qwwtlsq7x7ry8ytgsv4s5rmw8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM202RTMwclM1YllIdlBZ
        Z2tzRm1JSlJOL2pOcytxZmdBM0lLNGVzM1NvCnRxSWVoRkx0Q3R3VHBBNWRzNFVW
        ejd5bk5VS1BkdllOT2toalJNeE1kTE0KLS0tIDIzWUhOQ2EvQVA5OWtpbzJ4ajEv
        S1IzMVZiTnFFbnR2UlZWNFVSWmZNZTQKzm5pgHpFPd9X9naQOR6NnTlM7yGr0+XS
        kU7PeMT57wIa6+/7IPpy5CZ6xi0zMNLqZd7kp5BT0kDKr5lbHP4NCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T06:13:48Z"
  mac: ENC[AES256_GCM,data:EtqTlM1Ugf+1ko4Ogkc5EPrUS7E+EeNDCW1hVLIq9hEEt3btXTZYfEN+fkg0ZI//6d9PZzjk340lGqujc5t89+AnLAehJNpStCuGRfVxVBV/tPZlSK+ytZdNw+JST1tetimrciZGVCP/2Ox986fEurYKGmAhGsp4qqy7DCaDF+E=,iv:6i9cEC5XCP6XCsDeQjOsI4jb7c92bf2IYDlFpYxG/e8=,tag:1TfrfD0jiFmIqa3g/l5YXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
