apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bEjG8jJ/kuDxdoFb5TAZ3nGV8CYotw0vC92p1+QqqkoMRmt4BT71PA==,iv:/W+42NL4klqeWeH7fDpwKofoTzHfvV8N5F60P/Ykf7M=,tag:9Np5mxDVAprFSDylCUNtZg==,type:str]
sops:
  age:
    - recipient: age1qlgzet5vmw8vfxa2456rx5t6uhhjcph7qwwtlsq7x7ry8ytgsv4s5rmw8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSkRtK0k3dTk5KzB4eCtR
        MFBSMDhOZ3R5ek8yZC9meTNJL0ZKSElhWlZjCmVGTE45UHorQTVVbjBqWHhkRkNG
        clFpTnZXeGl4cWRTc1Z4QzhLNXU4N2sKLS0tIEdNV1F1U1JYcTkybDNPb2hPMFZF
        cldJbFdubXppNys2SitYNEprZXR3b0UKdRq/8iov/0EtsbY+1QnQ/uu/shtYM9tQ
        ZToN9OXXdGd5ri6CBd5+Ke0ph4Wohv02F/qsnDj5oR3lZ0wpIFqX1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T06:13:48Z"
  mac: ENC[AES256_GCM,data:O2kIlgp70zAsU2T6iYWMrjlTpjCTo3TRKZDAnYT2mGyus4dwzMO1bAtHHt3qBLxIudNJIj9Wj9bsZ6YMa4HJQMLrJKPV6FeQ2gKmknFddwwm3zRmbWwlv7zrqnmFAqPoR3OuQg5ucKYenYkZSewbceCgwi6PIzokJcY5qdruOfQ=,iv:gURuMKwZZuU5UbJQ+fVDsSkWNdHdGXFK2/VBdqkGa+U=,tag:Qj0mdVN+dv9JZHr4pWgMQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
